# Generated by Django 4.1.7 on 2023-03-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
